name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: latest

    - name: Install dependencies
      run: npm ci

    - name: Build the project
      run: npm run astro build

    - name: Deploy to Azure
      uses: azure/CLI@v2
      with:
        azcliversion: latest
        inlineScript: |
          az storage blob upload-batch --account-name gravelalvesstorage --source ./dist --destination '$web' --type block
      env:
        AZURE_STORAGE_ACCOUNT: gravelalvesstorage
        AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}