name: Build and Deploy to Azure

on:
  push:
    branches:
      - main
    paths-ignore: 
      - 'README.md'
      - '.vscode/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # needed due to sonarqube analysis
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: latest

    - name: Install dependencies
      run: npm ci

    - name: Build the project
      run: npm run astro build

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Deploy to Azure
      uses: azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        skip_app_build: true
        app_location: "./dist"
        output_location: ""