name: Validate Pull Requests

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: npm ci

    - name: Check the project
      run: npm run astro check

    - name: Build the project
      run: npm run astro build

    - name: Comment PR
      if: ${{ failure() }}
      uses: thollander/actions-comment-pull-request@main
      with:
        message: 'Build failed. Please check the logs for more details.'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}